language: java
jdk:
  - oraclejdk8

script: mvn clean package -DskipTests=true

before_deploy:
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key: $github_token
  skip_cleanup: true
  on:
    tags: true
