spring:
  mongodb:
    uri: mongodb://localhost:27017/test
  redis:
    host: 127.0.0.1
    hostName: 127.0.0.1
    port: 16379
    password: redis@bt.wbvNRa3tqygUjjNP

server:
  port: 8800

management:
  endpoint:
    conditions:
      enabled: true
    health:
      enabled: true
      cache:
        time-to-live: 5000

symphony:
  enable: true
  staticServerPath: /rs
  serverPath: /rs
  login:
    secret: ssssss
  tuling:
    api: http://www.tuling123.com/openapi/api
    apikey: 96c7f65aa25b497ba5a0f236881ba657
    secret: ae16601956ef4d8c
