spring:
  profiles:
    active: dev
  data:
    mongodb:
      database: test
      host: localhost
      port: 27017
  mvc:
    pathmatch:
      #FIX because "this.condition" is null ，退回老版本，待Springfox修复
      matching-strategy: ant_path_matcher

server:
  port: 8800

management:
  endpoint:
    conditions:
      enabled: true
    health:
      enabled: true
      cache:
        time-to-live: 5000

symphony:
  enable: true
  staticServerPath: /rs
  serverPath: /rs
  login:
    secret: ssssss
  tuling:
    api: http://www.tuling123.com/openapi/api
    apikey: 96c7f65aa25b497ba5a0f236881ba657
    secret: ae16601956ef4d8c
