spring:
  mongodb:
    uri: mongodb://localhost:27017/test
  redis:
    host: 127.0.0.1
    hostName: 127.0.0.1
    port: 16379
    password: redis@bt.wbvNRa3tqygUjjNP

server:
  serverPath: /spid
  port: 8800

management:
  endpoint:
    conditions:
      enabled: true
    health:
      enabled: true
      cache:
        time-to-live: 5000

# symphony:
#   enable: true
#   staticServerPath: /rs
#   serverPath: /rs
#   login:
#     secret: ssssss
#   tuling:
#     api: http://www.tuling123.com/openapi/api
#     apikey: 96c7f65aa25b497ba5a0f236881ba657
#     secret: ae16601956ef4d8c

# 公众号配置(必填)
wx.mp.appId: wx55d1cca59e29bbdb
wx.mp.secret: c9a00ce888ebefc7dd1e10ee1e69084a
wx.mp.token: redspider0407
wx.mp.aesKey: xxx
# 存储配置redis(可选)
wx.mp.config-storage.type: RedisTemplate                # 配置类型: Memory(默认), Jedis, RedisTemplate
wx.mp.config-storage.key-prefix: wx:cp                  # 相关redis前缀配置: wx(默认)
wx.mp.config-storage.redis.host: ${spring.redis.host}
wx.mp.config-storage.redis.port: ${spring.redis.port}
#单机和sentinel同时存在时，优先使用sentinel配置
#wx.mp.config-storage.redis.sentinel-ips: 127.0.0.1:16379,127.0.0.1:26379
#wx.mp.config-storage.redis.sentinel-name: mymaster
# http客户端配置
wx.mp.config-storage.http-client-type: httpclient      # http客户端类型: HttpClient(默认), OkHttp, JoddHttp
wx.mp.config-storage.http-proxy-host:
wx.mp.config-storage.http-proxy-port:
wx.mp.config-storage.http-proxy-username:
wx.mp.config-storage.http-proxy-password:
# 公众号地址host配置
#wx.mp.hosts.api-host: http://proxy.com/
#wx.mp.hosts.open-host: http://proxy.com/
#wx.mp.hosts.mp-host: http://proxy.com/
